# Dicionário de idiomas
translations = {
    "en": {
        "title": "Transient Response of Capacitor Energization Current",
        "voltage": "3𝝋 Voltage [kV]",
        "frequency": "Frequency [Hz]",
        "short_circuit_current": "Short-Circuit Current at the Bus [kA]",
        "number_of_banks": "Number of Banks",
        "safety_factor": "Safety Factor",
        "energize_bank": "#### Bank to be energized $(\\#0)$",
        "already_energized_banks": "#### Banks already energized $(\\#1$ to $\\#n)$",
        "results": "#### Results",
        "nominal_current": "Nominal current of the bank $I_{\\rm nominal}=$",
        "for_single_bank": "##### For single bank",
        "peak_current_energization": "Peak energization current $I_{\\rm{inrush}}=$",
        "oscillation_frequency": "Oscillation Frequency = ",
        "for_bank_with_others_energized": "##### For bank with other banks energized",
        "conclusion": "#### Conclusion",
        "conclusion_text": "Typical amplitudes of inrush currents for back-to-back capacitor bank energization are several ${\\rm kA}$ with frequencies from $2{\\rm~kHz}$ to $5{\\rm~kHz}$ [$^{[1]}$](https://ieeexplore.ieee.org/document/7035261).",
        "adequate_reactor": "Adequate reactor, as $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "not_adequate_reactor": "Reactor NOT adequate, as $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "bibliography": "#### Bibliography",
        "latex_report": "Latex Report (ZIP)",
        "development": "#### Development"
    },
    "pt": {
        "title": "Resposta transitória da corrente de energização de capacitores",
        "voltage": "Tensão 3𝝋 [kV]",
        "frequency": "Frequência [Hz]",
        "short_circuit_current": "Corrente de curto-circuito na barra [kA]",
        "number_of_banks": "Número de Bancos",
        "safety_factor": "Fator de Segurança",
        "energize_bank": "#### Banco a ser energizado $(\\#0)$",
        "already_energized_banks": "#### Bancos já energizados $(\\#1$ ao $\\#n)$",
        "results": "#### Resultados",
        "nominal_current": "Corrente nominal do banco $I_{\\rm nominal}=$",
        "for_single_bank": "##### Para banco único",
        "peak_current_energization": "Corrente de pico na energização $I_{\\rm{inrush}}=$",
        "oscillation_frequency": "Frequência de Oscilação = ",
        "for_bank_with_others_energized": "##### Para banco com os demais bancos energizados",
        "conclusion": "#### Conclusão",
        "conclusion_text": "As amplitudes típicas das correntes de *inrush* para energização *back-to-back* de bancos de capacitores são de vários ${\\rm kA}$ com frequências de $2{\\rm~kHz}$ a $5{\\rm~kHz}$ [$^{[1]}$](https://ieeexplore.ieee.org/document/7035261).",
        "adequate_reactor": "Reator adequado, pois $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "not_adequate_reactor": "Reator NÃO adequado, pois $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "bibliography": "#### Bibliografia",
        "latex_report": "Relatório Latex (ZIP)",
        "development": "#### Desenvolvimento"
    },
    "zh": {
        "title": "电容器充电电流的瞬态响应",
        "voltage": "三相电压 [kV]",
        "frequency": "频率 [Hz]",
        "short_circuit_current": "母线短路电流 [kA]",
        "number_of_banks": "电容器组数量",
        "safety_factor": "安全系数",
        "energize_bank": "#### 待激活的电容器组 $(\\#0)$",
        "already_energized_banks": "#### 已激活的电容器组 $(\\#1$ 到 $\\#n)$",
        "results": "#### 结果",
        "nominal_current": "电容器组的额定电流 $I_{\\rm nominal}=$",
        "for_single_bank": "##### 单个电容器组",
        "peak_current_energization": "激活的峰值电流 $I_{\\rm{inrush}}=$",
        "oscillation_frequency": "振荡频率 = ",
        "for_bank_with_others_energized": "##### 已激活的其他电容器组",
        "conclusion": "#### 结论",
        "conclusion_text": "电容器组背靠背激活时的典型浪涌电流幅度为几个 ${\\rm kA}$，频率为 $2{\\rm~kHz}$ 到 $5{\\rm~kHz}$ [$^{[1]}$](https://ieeexplore.ieee.org/document/7035261).",
        "adequate_reactor": "合适的反应堆，因为 $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "not_adequate_reactor": "反应堆不合适，因为 $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "bibliography": "#### 参考文献",
        "latex_report": "LaTeX 报告 (ZIP)",
        "development": "#### 发展"
    },
    "es": {
        "title": "Respuesta transitoria de la corriente de energización de condensadores",
        "voltage": "Voltaje 3𝝋 [kV]",
        "frequency": "Frecuencia [Hz]",
        "short_circuit_current": "Corriente de cortocircuito en la barra [kA]",
        "number_of_banks": "Número de Bancos",
        "safety_factor": "Factor de Seguridad",
        "energize_bank": "#### Banco a energizar $(\\#0)$",
        "already_energized_banks": "#### Bancos ya energizados $(\\#1$ a $\\#n)$",
        "results": "#### Resultados",
        "nominal_current": "Corriente nominal del banco $I_{\\rm nominal}=$",
        "for_single_bank": "##### Para banco único",
        "peak_current_energization": "Corriente de pico en la energización $I_{\\rm{inrush}}=$",
        "oscillation_frequency": "Frecuencia de Oscilación = ",
        "for_bank_with_others_energized": "##### Para banco con los demás bancos energizados",
        "conclusion": "#### Conclusión",
        "conclusion_text": "Las amplitudes típicas de las corrientes de irrupción para la energización de bancos de capacitores en modo back-to-back son de varios ${\\rm kA}$ con frecuencias de $2{\\rm~kHz}$ a $5{\\rm~kHz}$ [$^{[1]}$](https://ieeexplore.ieee.org/document/7035261).",
        "adequate_reactor": "Reactor adecuado, ya que $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "not_adequate_reactor": "Reactor NO adecuado, ya que $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "bibliography": "#### Bibliografía",
        "latex_report": "Informe Latex (ZIP)",
        "development": "#### Desarrollo"
    },
    "fr": {
        "title": "Réponse transitoire du courant d'enclenchement des condensateurs",
        "voltage": "Tension 3𝝋 [kV]",
        "frequency": "Fréquence [Hz]",
        "short_circuit_current": "Courant de court-circuit au bus [kA]",
        "number_of_banks": "Nombre de Bancs",
        "safety_factor": "Facteur de Sécurité",
        "energize_bank": "#### Banc à energiser $(\\#0)$",
        "already_energized_banks": "#### Bancs déjà energisés $(\\#1$ à $\\#n)$",
        "results": "#### Résultats",
        "nominal_current": "Courant nominal du banc $I_{\\rm nominal}=$",
        "for_single_bank": "##### Pour banc unique",
        "peak_current_energization": "Courant de crête lors de l'enclenchement $I_{\\rm{inrush}}=$",
        "oscillation_frequency": "Fréquence d'oscillation = ",
        "for_bank_with_others_energized": "##### Pour banc avec d'autres bancs energisés",
        "conclusion": "#### Conclusion",
        "conclusion_text": "Les amplitudes typiques des courants d'appel pour l'enclenchement back-to-back des bancs de condensateurs sont de plusieurs ${\\rm kA}$ avec des fréquences de $2{\\rm~kHz}$ à $5{\\rm~kHz}$ [$^{[1]}$](https://ieeexplore.ieee.org/document/7035261).",
        "adequate_reactor": "Réacteur adéquat, car $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "not_adequate_reactor": "Réacteur NON adéquat, car $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "bibliography": "#### Bibliographie",
        "latex_report": "Rapport Latex (ZIP)",
        "development": "#### Développement"
    },
    "de": {
        "title": "Übergangsantwort des Einschaltstroms von Kondensatoren",
        "voltage": "Spannung 3𝝋 [kV]",
        "frequency": "Frequenz [Hz]",
        "short_circuit_current": "Kurzschlussstrom an der Sammelschiene [kA]",
        "number_of_banks": "Anzahl der Bänke",
        "safety_factor": "Sicherheitsfaktor",
        "energize_bank": "#### Zu energisierender Bank $(\\#0)$",
        "already_energized_banks": "#### Bereits energisierte Banken $(\\#1$ bis $\\#n)$",
        "results": "#### Ergebnisse",
        "nominal_current": "Nennstrom des Banks $I_{\\rm nominal}=$",
        "for_single_bank": "##### Für einzelnen Bank",
        "peak_current_energization": "Spitzenstrom bei der Einschaltung $I_{\\rm{inrush}}=$",
        "oscillation_frequency": "Oszillationsfrequenz = ",
        "for_bank_with_others_energized": "##### Für Bank mit anderen energisierten Banken",
        "conclusion": "#### Schlussfolgerung",
        "conclusion_text": "Die typischen Amplituden der Einschaltströme für die Back-to-Back-Einschaltung von Kondensatorbänken betragen mehrere ${\\rm kA}$ mit Frequenzen von $2{\\rm~kHz}$ bis $5{\\rm~kHz}$ [$^{[1]}$](https://ieeexplore.ieee.org/document/7035261).",
        "adequate_reactor": "Geeigneter Reaktor, da $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "not_adequate_reactor": "Reaktor NICHT geeignet, da $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "bibliography": "#### Bibliographie",
        "latex_report": "LaTeX-Bericht (ZIP)",
        "development": "#### Entwicklung"
    }
}
